name: Generate Android Keystore
on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  generate-key:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Konfiguracja Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🔑 Wygenerowanie klucza Keystore przez GitHub
        run: |
          keytool -genkey -v -keystore my-upload-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000 -storepass "jkis66,?!#jakostakTobyl" -keypass "jkis66,?!#jakostakTobyl" -dname "CN=MyName, OU=MyOrg, O=MyCompany, L=MyCity, S=MyState, C=PL"

      - name: 💾 Udostępnienie pliku do pobrania
        uses: actions/upload-artifact@v4
        with:
          name: generated-keystore
          path: my-upload-key.keystore